/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElRate: typeof import('element-plus/es')['ElRate']
    ErrorAlertIcon: typeof import('./../src/components/common/ErrorBoundary/icon/ErrorAlertIcon.vue')['default']
    ErrorBoundary: typeof import('./../src/components/common/ErrorBoundary/index.vue')['default']
    HomeIcon: typeof import('./../src/components/common/ErrorBoundary/icon/HomeIcon.vue')['default']
    LazyLoadWrapper: typeof import('./../src/components/common/LazyLoadWrapper/index.vue')['default']
    PageChange: typeof import('./../src/components/common/PageChange/index.vue')['default']
    RetryIcon: typeof import('./../src/components/common/ErrorBoundary/icon/RetryIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
