// 文物类型选项
export const artifactTypes = [
  { label: "全部", value: "all" },
  { label: "绘画", value: "painting" },
  { label: "法书", value: "calligraphy" },
  { label: "碑帖", value: "rubbing" },
  { label: "铜器", value: "bronze" },
  { label: "金银器", value: "gold_silver" },
  { label: "陶瓷", value: "ceramic" },
  { label: "漆器", value: "lacquer" },
  { label: "珐琅器", value: "enamel" },
  { label: "玉石器", value: "jade" },
  { label: "雕塑", value: "sculpture" },
  { label: "陶俑", value: "terracotta" },
  { label: "织绣", value: "textile" },
  { label: "雕刻工艺", value: "carving" },
  { label: "其他工艺", value: "other_craft" },
  { label: "文具", value: "stationery" },
  { label: "生活用器", value: "daily" },
  { label: "钟表仪器", value: "clock" },
  { label: "珍宝", value: "treasure" },
  { label: "宗教文物", value: "religious" },
  { label: "武备仪仗", value: "weapon" },
  { label: "帝后玺册", value: "seal" },
  { label: "铭刻", value: "inscription" },
  { label: "外国文物", value: "foreign" },
  { label: "其他文物", value: "other" },
  { label: "古籍文献", value: "ancient_book" },
  { label: "古建筑藏品", value: "ancient_architecture" },
];

// 年代选项
export const periods = [
  { label: "全部", value: "all" },
  { label: "新石器时代", value: "neolithic" },
  { label: "夏", value: "xia" },
  { label: "商", value: "shang" },
  { label: "周", value: "zhou" },
  { label: "春秋", value: "spring_autumn" },
  { label: "战国", value: "warring_states" },
  { label: "秦", value: "qin" },
  { label: "汉", value: "han" },
  { label: "新莽", value: "xin" },
  { label: "三国", value: "three_kingdoms" },
  { label: "晋", value: "jin_dynasty" },
  { label: "南北朝", value: "northern_southern" },
  { label: "隋", value: "sui" },
  { label: "唐", value: "tang" },
  { label: "五代十国", value: "five_dynasties" },
  { label: "辽", value: "liao" },
  { label: "西夏", value: "western_xia" },
  { label: "宋", value: "song" },
  { label: "金", value: "jin_state" },
  { label: "元", value: "yuan" },
  { label: "明", value: "ming" },
  { label: "清", value: "qing" },
  { label: "民国", value: "republic" },
  { label: "近现代", value: "modern" },
  { label: "现当代", value: "contemporary" },
  { label: "其他", value: "other" },
];

// 年代映射关系
export const periodMap: Record<string, string[]> = {
  neolithic: ["新石器时代"],
  xia: ["夏"],
  shang: ["商"],
  zhou: ["周"],
  spring_autumn: ["春秋"],
  warring_states: ["战国"],
  qin: ["秦"],
  han: ["汉"],
  xin: ["新莽"],
  three_kingdoms: ["三国"],
  jin_dynasty: ["晋"],
  northern_southern: ["南北朝"],
  sui: ["隋"],
  tang: ["唐"],
  five_dynasties: ["五代十国"],
  liao: ["辽"],
  western_xia: ["西夏"],
  song: ["宋"],
  jin_state: ["金"],
  yuan: ["元"],
  ming: ["明"],
  qing: ["清"],
  republic: ["民国"],
  modern: ["近现代"],
  contemporary: ["现当代"],
  other: ["其他"],
};
