/**
 * TravelGuide 省份常量
 * 包含：中国34个省份/地区的基础信息
 */

export interface Province {
  id: string;
  name: string;
  nameEn: string;
  abbreviation: string;
  region: string;
  capital: string;
  description: string;
  image: string;
  tags: string[];
  bestTime: string;
  highlights: string[];
}

export const provincesData: Province[] = [
  {
    id: 'beijing',
    name: '北京',
    nameEn: 'Beijing',
    abbreviation: '京',
    region: '华北',
    capital: '北京市',
    description: '中国首都，拥有丰富的历史文化遗产和现代都市风貌，是世界著名的古都和国际大都市',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/1.webp',
    tags: ['历史', '文化', '古迹', '首都'],
    bestTime: '春秋两季',
    highlights: ['故宫', '长城', '天坛', '颐和园']
  },
  {
    id: 'shanghai',
    name: '上海',
    nameEn: 'Shanghai',
    abbreviation: '沪',
    region: '华东',
    capital: '上海市',
    description: '中国经济、金融、贸易、航运中心，现代化国际大都市，中西文化交融',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/2.webp',
    tags: ['现代', '都市', '金融', '文化'],
    bestTime: '春秋两季',
    highlights: ['外滩', '东方明珠', '豫园', '迪士尼乐园']
  },
  {
    id: 'guangdong',
    name: '广东',
    nameEn: 'Guangdong',
    abbreviation: '粤',
    region: '华南',
    capital: '广州市',
    description: '中国南大门，改革开放前沿，岭南文化发源地，美食天堂',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/3.webp',
    tags: ['美食', '文化', '经济', '沿海'],
    bestTime: '秋冬季节',
    highlights: ['广州塔', '长隆旅游度假区', '开平碉楼', '丹霞山']
  },
  {
    id: 'sichuan',
    name: '四川',
    nameEn: 'Sichuan',
    abbreviation: '蜀',
    region: '西南',
    capital: '成都市',
    description: '天府之国，熊猫故乡，川菜发源地，自然与人文景观丰富',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/4.webp',
    tags: ['熊猫', '美食', '自然', '文化'],
    bestTime: '春秋两季',
    highlights: ['九寨沟', '峨眉山', '都江堰', '成都大熊猫繁育研究基地']
  },
  {
    id: 'zhejiang',
    name: '浙江',
    nameEn: 'Zhejiang',
    abbreviation: '浙',
    region: '华东',
    capital: '杭州市',
    description: '鱼米之乡，丝绸之府，山水秀美，人文荟萃，经济发达',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/5.webp',
    tags: ['水乡', '古镇', '茶文化', '经济'],
    bestTime: '春秋两季',
    highlights: ['西湖', '乌镇', '普陀山', '千岛湖']
  },
  {
    id: 'jiangsu',
    name: '江苏',
    nameEn: 'Jiangsu',
    abbreviation: '苏',
    region: '华东',
    capital: '南京市',
    description: '江南水乡，园林甲天下，历史文化底蕴深厚，经济发达',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/6.webp',
    tags: ['园林', '水乡', '历史', '文化'],
    bestTime: '春秋两季',
    highlights: ['苏州园林', '中山陵', '瘦西湖', '周庄']
  },
  {
    id: 'shandong',
    name: '山东',
    nameEn: 'Shandong',
    abbreviation: '鲁',
    region: '华东',
    capital: '济南市',
    description: '孔孟之乡，礼仪之邦，泰山所在地，齐鲁文化发源地',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/7.webp',
    tags: ['儒家文化', '山海', '历史', '海滨'],
    bestTime: '春秋两季',
    highlights: ['泰山', '曲阜三孔', '青岛栈桥', '蓬莱阁']
  },
  {
    id: 'anhui',
    name: '安徽',
    nameEn: 'Anhui',
    abbreviation: '皖',
    region: '华东',
    capital: '合肥市',
    description: '徽州文化发源地，黄山闻名天下，文房四宝之乡',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/8.webp',
    tags: ['徽派建筑', '山水', '文化', '茶叶'],
    bestTime: '春秋两季',
    highlights: ['黄山', '宏村', '西递', '九华山']
  },
  {
    id: 'chongqing',
    name: '重庆',
    nameEn: 'Chongqing',
    abbreviation: '渝',
    region: '西南',
    capital: '重庆市',
    description: '山城、江城、雾都，巴渝文化发源地，火锅之城',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/9.webp',
    tags: ['山城', '火锅', '夜景', '长江'],
    bestTime: '春秋两季',
    highlights: ['洪崖洞', '解放碑', '长江三峡', '武隆天生三桥']
  },
  {
    id: 'fujian',
    name: '福建',
    nameEn: 'Fujian',
    abbreviation: '闽',
    region: '华东',
    capital: '福州市',
    description: '海上丝绸之路起点，闽南文化，土楼奇观，茶乡福建',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/10.webp',
    tags: ['土楼', '茶文化', '海滨', '侨乡'],
    bestTime: '春秋两季',
    highlights: ['厦门鼓浪屿', '武夷山', '福建土楼', '泉州古城']
  },
  {
    id: 'gansu',
    name: '甘肃',
    nameEn: 'Gansu',
    abbreviation: '甘',
    region: '西北',
    capital: '兰州市',
    description: '丝绸之路黄金段，敦煌莫高窟所在地，多元文化交融',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/11.webp',
    tags: ['丝路文化', '沙漠', '石窟', '历史'],
    bestTime: '夏秋季节',
    highlights: ['敦煌莫高窟', '鸣沙山月牙泉', '张掖丹霞', '嘉峪关']
  },
  {
    id: 'guangxi',
    name: '广西',
    nameEn: 'Guangxi',
    abbreviation: '桂',
    region: '华南',
    capital: '南宁市',
    description: '壮族自治区，桂林山水甲天下，喀斯特地貌典型代表',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/12.webp',
    tags: ['喀斯特', '山水', '少数民族', '边境'],
    bestTime: '春秋两季',
    highlights: ['漓江', '阳朔西街', '龙脊梯田', '北海银滩']
  },
  {
    id: 'guizhou',
    name: '贵州',
    nameEn: 'Guizhou',
    abbreviation: '黔',
    region: '西南',
    capital: '贵阳市',
    description: '公园省，多彩贵州，苗族侗族文化浓郁，瀑布溶洞众多',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/13.webp',
    tags: ['少数民族', '瀑布', '溶洞', '山地'],
    bestTime: '春秋两季',
    highlights: ['黄果树瀑布', '千户苗寨', '荔波小七孔', '镇远古镇']
  },
  {
    id: 'hainan',
    name: '海南',
    nameEn: 'Hainan',
    abbreviation: '琼',
    region: '华南',
    capital: '海口市',
    description: '热带海岛，椰风海韵，国际旅游岛，天涯海角',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/14.webp',
    tags: ['热带', '海岛', '度假', '海滨'],
    bestTime: '冬春季节',
    highlights: ['三亚亚龙湾', '天涯海角', '南山寺', '蜈支洲岛']
  },
  {
    id: 'hebei',
    name: '河北',
    nameEn: 'Hebei',
    abbreviation: '冀',
    region: '华北',
    capital: '石家庄市',
    description: '环绕京津，燕赵之地，长城精华段，承德避暑山庄',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/15.webp',
    tags: ['历史', '长城', '皇家园林', '文化'],
    bestTime: '春秋两季',
    highlights: ['承德避暑山庄', '山海关', '北戴河', '白洋淀']
  },
  {
    id: 'heilongjiang',
    name: '黑龙江',
    nameEn: 'Heilongjiang',
    abbreviation: '黑',
    region: '东北',
    capital: '哈尔滨市',
    description: '冰雪王国，北国风光，中俄边境，欧陆风情',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/16.webp',
    tags: ['冰雪', '边境', '森林', '欧式建筑'],
    bestTime: '冬夏两季',
    highlights: ['哈尔滨冰雪大世界', '漠河北极村', '五大连池', '镜泊湖']
  },
  {
    id: 'henan',
    name: '河南',
    nameEn: 'Henan',
    abbreviation: '豫',
    region: '华中',
    capital: '郑州市',
    description: '中原腹地，华夏文明发源地，少林功夫，甲骨文故乡',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/17.webp',
    tags: ['中原文化', '历史', '武术', '考古'],
    bestTime: '春秋两季',
    highlights: ['龙门石窟', '少林寺', '殷墟', '云台山']
  },
  {
    id: 'hubei',
    name: '湖北',
    nameEn: 'Hubei',
    abbreviation: '鄂',
    region: '华中',
    capital: '武汉市',
    description: '千湖之省，荆楚文化，三峡工程所在地，三国文化',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/18.webp',
    tags: ['湖泊', '长江', '三国文化', '历史'],
    bestTime: '春秋两季',
    highlights: ['武汉黄鹤楼', '神农架', '武当山', '宜昌三峡']
  },
  {
    id: 'hunan',
    name: '湖南',
    nameEn: 'Hunan',
    abbreviation: '湘',
    region: '华中',
    capital: '长沙市',
    description: '芙蓉国，潇湘文化，张家界奇观，湘菜辣味天下',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/19.webp',
    tags: ['山水', '美食', '红色文化', '少数民族'],
    bestTime: '春秋两季',
    highlights: ['张家界', '凤凰古城', '岳麓书院', '衡山']
  },
  {
    id: 'jiangxi',
    name: '江西',
    nameEn: 'Jiangxi',
    abbreviation: '赣',
    region: '华东',
    capital: '南昌市',
    description: '红色故里，瓷都景德镇，庐山仙境，鄱阳湖候鸟天堂',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/20.webp',
    tags: ['红色文化', '陶瓷', '山水', '革命历史'],
    bestTime: '春秋两季',
    highlights: ['庐山', '井冈山', '景德镇', '婺源油菜花']
  },
  {
    id: 'jilin',
    name: '吉林',
    nameEn: 'Jilin',
    abbreviation: '吉',
    region: '东北',
    capital: '长春市',
    description: '白山黑水，雾凇之都，长白山天池，朝鲜族风情',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/21.webp',
    tags: ['冰雪', '长白山', '雾凇', '边境'],
    bestTime: '冬夏两季',
    highlights: ['长白山天池', '吉林雾凇', '长春电影城', '伪满皇宫']
  },
  {
    id: 'liaoning',
    name: '辽宁',
    nameEn: 'Liaoning',
    abbreviation: '辽',
    region: '东北',
    capital: '沈阳市',
    description: '共和国长子，工业基地，满清发祥地，海滨城市大连',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/22.webp',
    tags: ['工业', '历史', '海滨', '满族文化'],
    bestTime: '春秋两季',
    highlights: ['沈阳故宫', '大连星海广场', '本溪水洞', '千山']
  },
  {
    id: 'neimenggu',
    name: '内蒙古',
    nameEn: 'Inner Mongolia',
    abbreviation: '蒙',
    region: '华北',
    capital: '呼和浩特市',
    description: '辽阔草原，蒙古族风情，成吉思汗故乡，草原文化',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/23.webp',
    tags: ['草原', '蒙古族', '沙漠', '边境'],
    bestTime: '夏秋季节',
    highlights: ['呼伦贝尔草原', '额济纳胡杨林', '响沙湾', '成吉思汗陵']
  },
  {
    id: 'ningxia',
    name: '宁夏',
    nameEn: 'Ningxia',
    abbreviation: '宁',
    region: '西北',
    capital: '银川市',
    description: '塞上江南，回族自治区，西夏王朝遗址，黄河文明',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/24.webp',
    tags: ['黄河', '回族文化', '沙漠', '西夏历史'],
    bestTime: '夏秋季节',
    highlights: ['沙坡头', '西夏王陵', '沙湖', '贺兰山岩画']
  },
  {
    id: 'qinghai',
    name: '青海',
    nameEn: 'Qinghai',
    abbreviation: '青',
    region: '西北',
    capital: '西宁市',
    description: '世界屋脊，三江源头，藏族文化，高原风光',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/25.webp',
    tags: ['高原', '湖泊', '藏族', '盐湖'],
    bestTime: '夏秋季节',
    highlights: ['青海湖', '塔尔寺', '茶卡盐湖', '可可西里']
  },
  {
    id: 'shaanxi',
    name: '陕西',
    nameEn: 'Shaanxi',
    abbreviation: '陕',
    region: '西北',
    capital: '西安市',
    description: '十三朝古都，兵马俑故乡，丝绸之路起点，中华文明摇篮',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/26.webp',
    tags: ['古都', '历史', '兵马俑', '丝路文化'],
    bestTime: '春秋两季',
    highlights: ['秦始皇兵马俑', '华清池', '大雁塔', '华山']
  },
  {
    id: 'shanxi',
    name: '山西',
    nameEn: 'Shanxi',
    abbreviation: '晋',
    region: '华北',
    capital: '太原市',
    description: '表里山河，晋商文化，古建博物馆，煤炭大省',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/27.webp',
    tags: ['古建筑', '晋商', '历史', '佛教'],
    bestTime: '春秋两季',
    highlights: ['平遥古城', '云冈石窟', '五台山', '乔家大院']
  },
  {
    id: 'taiwan',
    name: '台湾',
    nameEn: 'Taiwan',
    abbreviation: '台',
    region: '华东',
    capital: '台北市',
    description: '宝岛台湾，阿里山日月潭，中华文化传承，海峡两岸',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/28.webp',
    tags: ['岛屿', '中华文化', '热带', '海峡'],
    bestTime: '全年适宜',
    highlights: ['台北101', '日月潭', '阿里山', '垦丁国家公园']
  },
  {
    id: 'tianjin',
    name: '天津',
    nameEn: 'Tianjin',
    abbreviation: '津',
    region: '华北',
    capital: '天津市',
    description: '直辖市，欧式建筑群，相声之乡，狗不理包子',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/29.webp',
    tags: ['欧式建筑', '小吃', '港口', '文化'],
    bestTime: '春秋两季',
    highlights: ['天津之眼', '古文化街', '意式风情区', '盘山']
  },
  {
    id: 'xizang',
    name: '西藏',
    nameEn: 'Tibet',
    abbreviation: '藏',
    region: '西南',
    capital: '拉萨市',
    description: '世界屋脊，雪域高原，藏传佛教圣地，纯净天堂',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/30.webp',
    tags: ['高原', '宗教', '雪山', '藏族文化'],
    bestTime: '夏秋季节',
    highlights: ['布达拉宫', '大昭寺', '纳木错', '珠穆朗玛峰']
  },
  {
    id: 'xinjiang',
    name: '新疆',
    nameEn: 'Xinjiang',
    abbreviation: '新',
    region: '西北',
    capital: '乌鲁木齐市',
    description: '西域风情，瓜果之乡，丝绸之路要道，多元民族文化',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/31.webp',
    tags: ['西域文化', '沙漠', '葡萄', '少数民族'],
    bestTime: '夏秋季节',
    highlights: ['天山天池', '喀纳斯湖', '吐鲁番火焰山', '喀什老城']
  },
  {
    id: 'yunnan',
    name: '云南',
    nameEn: 'Yunnan',
    abbreviation: '滇',
    region: '西南',
    capital: '昆明市',
    description: '彩云之南，动植物王国，多民族聚居，四季如春',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/32.webp',
    tags: ['民族', '自然', '花卉', '边境'],
    bestTime: '全年适宜',
    highlights: ['丽江古城', '大理古城', '玉龙雪山', '西双版纳']
  },
  {
    id: 'hongkong',
    name: '香港',
    nameEn: 'Hong Kong',
    abbreviation: '港',
    region: '华南',
    capital: '香港特别行政区',
    description: '东方之珠，国际金融中心，购物天堂，中西文化交汇',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/34.webp',
    tags: ['购物', '金融', '都市', '文化'],
    bestTime: '秋冬季节',
    highlights: ['维多利亚港', '太平山顶', '迪士尼乐园', '海洋公园']
  },
  {
    id: 'macau',
    name: '澳门',
    nameEn: 'Macau',
    abbreviation: '澳',
    region: '华南',
    capital: '澳门特别行政区',
    description: '海上花园，博彩业中心，中葡文化交融，历史城区',
    image: 'https://mouthhard-website.oss-cn-hangzhou.aliyuncs.com/landscape/35.webp',
    tags: ['博彩', '历史', '葡萄牙文化', '海滨'],
    bestTime: '秋冬季节',
    highlights: ['大三巴牌坊', '威尼斯人', '妈祖庙', '澳门塔']
  }
];

export default provincesData;
