/**
 * Museum 文物常量
 * 参照故宫博物院藏品分类体系（绘画、法书、碑帖、铜器、金银器、漆器、珐琅器、
 * 玉石器、雕塑、陶瓷、织绣、雕刻工艺、文具、钟表仪器、
 * 珍宝、宗教文物、武备仪仗、帝后玺印、铭刻等）
 *
 * 分类和年代是全局固定的，不随博物馆变化。
 */

// 文物类型常量 — 固定分类体系，首位为"全部"
export const ARTIFACT_TYPES = [
  { value: 'all', label: '全部文物' },
  { value: 'painting', label: '绘画' },
  { value: 'calligraphy', label: '法书' },
  { value: 'stele', label: '碑帖' },
  { value: 'bronze', label: '铜器' },
  { value: 'gold_silver', label: '金银器' },
  { value: 'lacquer', label: '漆器' },
  { value: 'enamel', label: '珐琅器' },
  { value: 'jade', label: '玉石器' },
  { value: 'sculpture', label: '雕塑' },
  { value: 'ceramic', label: '陶瓷' },
  { value: 'textile', label: '织绣' },
  { value: 'carving', label: '雕刻工艺' },
  { value: 'other_craft', label: '其他工艺' },
  { value: 'stationery', label: '文具' },
  { value: 'daily_use', label: '生活用具' },
  { value: 'clock', label: '钟表仪器' },
  { value: 'treasure', label: '珍宝' },
  { value: 'religious', label: '宗教文物' },
  { value: 'weapon', label: '武备仪仗' },
  { value: 'seal', label: '帝后玺册' },
  { value: 'inscription', label: '铭刻' },
  { value: 'foreign', label: '外国文物' },
  { value: 'other_artifact', label: '其他文物' },
  { value: 'ancient_book', label: '古籍文献' },
  { value: 'architecture', label: '古建藏品' },
] as const;

// 文物朝代常量 — 固定时间线，首位为"全部"
export const DYNASTIES = [
  { value: 'all', label: '全部年代' },
  { value: 'neolithic', label: '新石器时代' },
  { value: 'xia', label: '夏' },
  { value: 'shang', label: '商' },
  { value: 'zhou', label: '周' },
  { value: 'spring_autumn', label: '春秋' },
  { value: 'warring', label: '战国' },
  { value: 'qin', label: '秦' },
  { value: 'han', label: '汉' },
  { value: 'xinmang', label: '新莽' },
  { value: 'three_kingdoms', label: '三国' },
  { value: 'jin', label: '晋' },
  { value: 'southern_northern', label: '南北朝' },
  { value: 'sui', label: '隋' },
  { value: 'tang', label: '唐' },
  { value: 'five_dynasties', label: '五代十国' },
  { value: 'liao', label: '辽' },
  { value: 'western_xia', label: '西夏' },
  { value: 'song', label: '宋' },
  { value: 'jin_dynasty', label: '金' },
  { value: 'yuan', label: '元' },
  { value: 'ming', label: '明' },
  { value: 'qing', label: '清' },
  { value: 'republic', label: '民国' },
  { value: 'modern', label: '近现代' },
  { value: 'contemporary', label: '现当代' },
  { value: 'other', label: '其他' },
] as const;

// 文物类型映射 (英文 value → 中文 label)，用于筛选匹配
export const ARTIFACT_TYPE_MAP: Record<string, string[]> = {
  all: [],
  painting: ['绘画', '国画', '油画'],
  calligraphy: ['法书', '书法', '书法作品'],
  stele: ['碑帖', '碑刻'],
  bronze: ['铜器', '青铜器', '青铜礼器'],
  gold_silver: ['金银器', '金器', '银器', '金饰'],
  lacquer: ['漆器', '漆木器'],
  enamel: ['珐琅器', '景泰蓝'],
  jade: ['玉石器', '玉器', '玉雕', '玉石'],
  sculpture: ['雕塑', '石雕', '泥塑', '石刻'],
  ceramic: ['陶瓷', '陶瓷器', '瓷器', '青花瓷', '白瓷', '青瓷', '陶器', '彩陶'],
  textile: ['织绣', '织锦', '刺绣', '丝织品', '帛画', '锦缎', '蜡染'],
  carving: ['雕刻工艺', '竹雕', '木雕', '牙雕', '骨雕', '石雕工艺品'],
  other_craft: ['其他工艺', '工艺品'],
  stationery: ['文具', '文房四宝', '墨', '砚台', '徽墨'],
  daily_use: ['生活用具', '日用器具', '家具'],
  clock: ['钟表仪器', '钟表', '仪器'],
  treasure: ['珍宝', '珠宝', '宝石'],
  religious: ['宗教文物', '佛教文物', '道教文物', '佛像', '法器'],
  weapon: ['武备仪仗', '兵器', '武器', '铠甲', '刀剑'],
  seal: ['帝后玺册', '帝后玺印', '玺印', '印章', '符牌', '虎符'],
  inscription: ['铭刻', '金文', '铭文'],
  foreign: ['外国文物', '外销瓷', '舶来品'],
  other_artifact: ['其他文物', '其他', '杂项', '科技文物', '砖画', '画像砖', '砖刻'],
  ancient_book: ['古籍文献', '古籍', '善本', '拓片'],
  architecture: ['古建藏品', '建筑构件', '砖瓦', '石阙'],
};

// 朝代映射 (英文 value → 中文 period 值数组)，支持多值匹配
export const DYNASTY_MAP: Record<string, string[]> = {
  all: [],
  neolithic: ['新石器时代', '红山文化', '龙山文化', '仰韶文化', '马家窑', '良渚文化', '辛店文化', '卡若文化'],
  xia: ['夏'],
  shang: ['商', '商代'],
  zhou: ['西周', '东周', '周'],
  spring_autumn: ['春秋'],
  warring: ['战国'],
  qin: ['秦', '秦代'],
  han: ['西汉', '东汉', '汉代'],
  xinmang: ['新莽'],
  three_kingdoms: ['三国'],
  jin: ['晋'],
  southern_northern: ['南北朝', '南朝', '北朝', '北魏'],
  sui: ['隋'],
  tang: ['唐', '唐代'],
  five_dynasties: ['五代', '五代十国'],
  liao: ['辽', '辽代'],
  western_xia: ['西夏'],
  song: ['北宋', '南宋', '宋'],
  jin_dynasty: ['金', '金代'],
  yuan: ['元', '元代'],
  ming: ['明', '明代'],
  qing: ['清', '清代', '明清'],
  republic: ['民国'],
  modern: ['近现代'],
  contemporary: ['当代', '现当代'],
  other: [
    '高句丽', '渤海国', '大理国',
    '卡若文化', '清代（跨明清两代）',
    '1949年至今',
  ],
};
